// colors

$cl-black:					<?= get_field('cl_black', 'option') 					? get_field('cl_black', 'option') 			: '#000000'; ?>;
$cl-white:					<?= get_field('cl_white', 'option') 					? get_field('cl_white', 'option') 			: '#ffffff'; ?>;
$cl-grey:					<?= get_field('cl_grey', 'option') 						? get_field('cl_grey', 'option') 			: '#eeeeee'; ?>;
$cl-primary:				<?= get_field('cl_primary', 'option') 					? get_field('cl_primary', 'option') 		: '#C6006D'; ?>;
$cl-primary-text:			<?= get_field('cl_primary_text', 'option') 				? get_field('cl_primary_text', 'option') 	: '$cl-black'; ?>;
$cl-secondary:				<?= get_field('cl_secondary', 'option') 				? get_field('cl_secondary', 'option') 		: '#5F207A'; ?>;
$cl-secondary-text:			<?= get_field('cl_secondary_text', 'option') 			? get_field('cl_secondary_text', 'option') 	: '$cl-black'; ?>;
$cl-error:					<?= get_field('cl_error', 'option') 					? get_field('cl_error', 'option') 			: '#EA4335'; ?>;
				
// font size						
				
$fs-tiny:					<?= get_field('fs_small', 'option') 					? get_field('fs_small', 'option') * 0.75 	: 16 * 0.75; ?>px;
$fs-small:					<?= get_field('fs_small', 'option') 					? get_field('fs_small', 'option') 			: 16; ?>px;
$fs-medium:					<?= get_field('fs_small', 'option') 					? get_field('fs_small', 'option') *	1.25	: 16 * 1.25; ?>px;
$fs-large:					<?= get_field('fs_small', 'option') 					? get_field('fs_small', 'option') *	1.5		: 16 * 1.5; ?>px;
$fs-huge:					<?= get_field('fs_small', 'option') 					? get_field('fs_small', 'option') *	2		: 16 * 2; ?>px;
				
// letter spacing				
				
$ls_medium:					<?= get_field('ls_medium', 'option') 					? get_field('ls_medium', 'option')			: 0.6; ?>px;
				
// line-height				
				
$lh-small:					<?= get_field('lh_large', 'option') 					? get_field('lh_large', 'option') * 0.6		: 1.2; ?>;
$lh-medium: 				<?= get_field('lh_large', 'option') 					? get_field('lh_large', 'option') *	0.8		: 1.6; ?>;
$lh-large: 					<?= get_field('lh_large', 'option') 					? get_field('lh_large', 'option')			: 2.0; ?>;
				
// font weight						
				
$fw-light:					<?= get_field('fw_light', 'option') 					? get_field('fw_light', 'option') 			: '300'; ?>;
$fw-regular:				<?= get_field('fw_regular', 'option') 					? get_field('fw_regular', 'option') 		: '400'; ?>;
$fw-medium:					<?= get_field('fw_medium', 'option') 					? get_field('fw_medium', 'option') 			: '600'; ?>;
$fw-bold:					<?= get_field('fw_bold', 'option') 						? get_field('fw_bold', 'option') 			: '700'; ?>;
				
// font family					
				
$ff-primary:				<?= get_field('ff_primary', 'option') 					? get_field('ff_primary', 'option') 		: "'lexia', serif"; ?>;
$ff-secondary:				<?= get_field('ff_secondary', 'option') 				? get_field('ff_secondary', 'option') 		: "'Lato', sans-serif"; ?>;

// border radius

$br-rectangle-top-left:		<?= get_field('br_rectangle_top_left', 'option') 		? get_field('br_rectangle_top_left', 'option') 		: '0'; ?>px;
$br-rectangle-top-right:	<?= get_field('br_rectangle_top_right', 'option') 		? get_field('br_rectangle_top_right', 'option') 	: '0'; ?>px;
$br-rectangle-bottom-right:	<?= get_field('br_rectangle_bottom_right', 'option') 	? get_field('br_rectangle_bottom_right', 'option') 	: '0'; ?>px;
$br-rectangle-bottom-left:	<?= get_field('br_rectangle_bottom_left', 'option') 	? get_field('br_rectangle_bottom_left', 'option') 	: '0'; ?>px;

$br-square-top-left:		<?= get_field('br_square_top_left', 'option') 			? get_field('br_square_top_left', 'option') 		: '0'; ?>px;
$br-square-top-right:		<?= get_field('br_square_top_right', 'option') 			? get_field('br_square_top_right', 'option') 	: '0'; ?>px;
$br-square-bottom-right:	<?= get_field('br_square_bottom_right', 'option') 		? get_field('br_square_bottom_right', 'option') 	: '0'; ?>px;
$br-square-bottom-left:		<?= get_field('br_square_bottom_left', 'option') 		? get_field('br_square_bottom_left', 'option') 	: '0'; ?>px;

// animation

$preferred-animation:       <?= get_field('animation', 'option')                    ? get_field('animation', 'option')              : 'none'; ?>;

<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5c2c7fd438dfe',
        'title' => 'Options',
        'fields' => array(
            array(
                'key' => 'field_5cee6ea37f679',
                'label' => 'Contact',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5c503393e5774',
                'label' => 'Company',
                'name' => 'options_company',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c2c7fd43c9dc',
                'label' => 'Phone number',
                'name' => 'options_phone_number',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c50303382b61',
                'label' => 'Email address',
                'name' => 'options_email_address',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c38a317c0695',
                'label' => 'Street',
                'name' => 'options_street',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c38a3f3c0697',
                'label' => 'Postal code',
                'name' => 'options_postal_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c38a40fc0698',
                'label' => 'City',
                'name' => 'options_city',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_606dbfef766f6',
                'label' => 'Google Maps API Key',
                'name' => 'options_maps_key',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cee7b85dbbbf',
                'label' => 'Header',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5cee7b97dbbc2',
                'label' => 'Align',
                'name' => 'options_header_align',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'normal' => 'Normal',
                    'top' => 'Top',
                    'button' => 'Button',
                ),
                'default_value' => 'Normal',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d4aa92ea4a2e',
                'label' => 'Logo',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5cee6f29f0796',
                'label' => 'Logo',
                'name' => 'options_logo',
                'type' => 'image',
                'instructions' => '280 x 80 px',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5cee6f38f0797',
                'label' => 'Logo alt',
                'name' => 'options_logo_alt',
                'type' => 'image',
                'instructions' => '280 x 80 px',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5d4aa948a4a2f',
                'label' => 'Search',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5cee6f98bdef6',
                'label' => 'Search',
                'name' => 'options_search',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => 'Show',
                'ui_off_text' => 'Hide',
            ),
            array(
                'key' => 'field_5cee6fcbd300b',
                'label' => 'Social',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5cee6fcfd300c',
                'label' => 'Facebook link',
                'name' => 'options_facebook_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d4ab62a8f211',
                'label' => 'Facebook page',
                'name' => 'options_facebook_page',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d4ab6358f212',
                'label' => 'Facebook access token',
                'name' => 'options_facebook_access_token',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cee6fdcd300d',
                'label' => 'Twitter link',
                'name' => 'options_twitter_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cee6fecd300e',
                'label' => 'LinkedIn link',
                'name' => 'options_linkedin_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cee6ff8d300f',
                'label' => 'Instagram link',
                'name' => 'options_instagram_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cee779bf2e6f',
                'label' => 'Youtube link',
                'name' => 'options_youtube_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d4ab5b58f210',
                'label' => 'Login',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5cee6eeef0793',
                'label' => 'Login',
                'name' => 'options_login',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_5d39be870d210',
                'label' => 'Privacy',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5cee6f63686c7',
                'label' => 'Privacy',
                'name' => 'options_privacy',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_5d403ed78e403',
                'label' => 'Tag manager',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5d403ee58e404',
                'label' => 'Head',
                'name' => 'options_tag_manager_head',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5d403eeb8e405',
                'label' => 'Body',
                'name' => 'options_tag_manager_body',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_602e69acf1c5a',
                'label' => 'Customize',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_602e6a2bf1c5c',
                'label' => 'Colors',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_602e6a4cf1c5d',
                'label' => 'Black',
                'name' => 'cl_black',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
            ),
            array(
                'key' => 'field_602e6a57f1c5e',
                'label' => 'White',
                'name' => 'cl_white',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#ffffff',
            ),
            array(
                'key' => 'field_602e6a5ef1c5f',
                'label' => 'Grey',
                'name' => 'cl_grey',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#eeeeee',
            ),
            array(
                'key' => 'field_602e6a65f1c60',
                'label' => 'Primary',
                'name' => 'cl_primary',
                'type' => 'color_picker',
                'instructions' => 'Pick a color that goes well on black',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '51',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#5F207A',
            ),
            array(
                'key' => 'field_602e8b5a3d9db',
                'label' => 'Primary text',
                'name' => 'cl_primary_text',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '49',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    '$cl-black' => 'Black',
                    '$cl-white' => 'White',
                ),
                'default_value' => '$cl-black',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_602e6a6df1c61',
                'label' => 'Secondary',
                'name' => 'cl_secondary',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '51',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#C6006D',
            ),
            array(
                'key' => 'field_602e8b8c3d9dc',
                'label' => 'Secondary text',
                'name' => 'cl_secondary_text',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '49',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    '$cl-black' => 'Black',
                    '$cl-white' => 'White',
                ),
                'default_value' => '$cl-black',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_602e6a75f1c62',
                'label' => 'Error',
                'name' => 'cl_error',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#EA4335',
            ),
            array(
                'key' => 'field_602e6a7ef1c63',
                'label' => 'Font size',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_602e6a8ff1c64',
                'label' => 'Small',
                'name' => 'fs_small',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 16,
                'placeholder' => 16,
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '1.0',
            ),
            array(
                'key' => 'field_602fb7d160905',
                'label' => 'Letter spacing',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_602fb79b60904',
                'label' => 'Medium',
                'name' => 'ls_medium',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '0.6',
                'placeholder' => '0.6',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '0.1',
            ),
            array(
                'key' => 'field_602fb7eb60906',
                'label' => 'Line height',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_602fb7f960907',
                'label' => 'Line height',
                'name' => 'lh_large',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '2.0',
                'placeholder' => '2.0',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '0.1',
            ),
            array(
                'key' => 'field_602e6ad0f1c65',
                'label' => 'Font weight',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_602e6adef1c66',
                'label' => 'Light',
                'name' => 'fw_light',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 300,
                'placeholder' => 300,
                'prepend' => '',
                'append' => '',
                'min' => 100,
                'max' => 900,
                'step' => 100,
            ),
            array(
                'key' => 'field_602e6ae6f1c67',
                'label' => 'Regular',
                'name' => 'fw_regular',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 400,
                'placeholder' => 400,
                'prepend' => '',
                'append' => '',
                'min' => 100,
                'max' => 900,
                'step' => 100,
            ),
            array(
                'key' => 'field_602e6aeef1c68',
                'label' => 'Medium',
                'name' => 'fw_medium',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 600,
                'placeholder' => 600,
                'prepend' => '',
                'append' => '',
                'min' => 100,
                'max' => 900,
                'step' => 100,
            ),
            array(
                'key' => 'field_602e6af6f1c69',
                'label' => 'Bold',
                'name' => 'fw_bold',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 700,
                'placeholder' => 700,
                'prepend' => '',
                'append' => '',
                'min' => 100,
                'max' => 900,
                'step' => 100,
            ),
            array(
                'key' => 'field_602e6afff1c6a',
                'label' => 'Font family',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_602e6b12f1c6b',
                'label' => 'Primary',
                'name' => 'ff_primary',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '\'lexia\', serif',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_602e6b1cf1c6c',
                'label' => 'Primary url',
                'name' => 'ff_primary_url',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://use.typekit.net/kll4grl.css',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_602e6b33f1c6d',
                'label' => 'Secondary',
                'name' => 'ff_secondary',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '\'Lato\', sans-serif',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_602e6b3bf1c6e',
                'label' => 'Secondary url',
                'name' => 'ff_secondary_url',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://fonts.googleapis.com/css?family=Lato:300,400,700,900',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_602e8cf989aaa',
                'label' => 'Border radius',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_602e8d0189aab',
                'label' => 'Rectangle Top left',
                'name' => 'br_rectangle_top_left',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_602e8ef389aac',
                'label' => 'Rectangle Top right',
                'name' => 'br_rectangle_top_right',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_602e8fb089aaf',
                'label' => 'Rectangle Bottom left',
                'name' => 'br_rectangle_bottom_left',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_602e8f2889aad',
                'label' => 'Rectangle Bottom right',
                'name' => 'br_rectangle_bottom_right',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_602fc161db6aa',
                'label' => 'Square Top left',
                'name' => 'br_square_top_left',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_602fc165db6ab',
                'label' => 'Square Top right',
                'name' => 'br_square_top_right',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_602fc16adb6ac',
                'label' => 'Square Bottom left',
                'name' => 'br_square_bottom_left',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_602fc16edb6ad',
                'label' => 'Square Bottom right',
                'name' => 'br_square_bottom_right',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_60a4bf13209e2',
                'label' => 'Animation',
                'name' => 'animation',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'none' => 'None',
                    'rotate' => 'Wiggle',
                    'pulse' => 'Pulse',
                ),
                'default_value' => 'none',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;

    ?>